/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICapabilityRegistry,
  ICapabilityRegistryInterface,
} from "../../JobEscrow.sol/ICapabilityRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "agent",
        type: "address",
      },
      {
        internalType: "bool",
        name: "success",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "jobValue",
        type: "uint256",
      },
    ],
    name: "updateReputation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICapabilityRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): ICapabilityRegistryInterface {
    return new Interface(_abi) as ICapabilityRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICapabilityRegistry {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ICapabilityRegistry;
  }
}
