/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace JobEscrow {
  export type BidStruct = {
    jobId: BytesLike;
    specialist: AddressLike;
    bidPrice: BigNumberish;
    timestamp: BigNumberish;
  };

  export type BidStructOutput = [
    jobId: string,
    specialist: string,
    bidPrice: bigint,
    timestamp: bigint
  ] & {
    jobId: string;
    specialist: string;
    bidPrice: bigint;
    timestamp: bigint;
  };

  export type JobStruct = {
    id: BytesLike;
    parentJobId: BytesLike;
    planner: AddressLike;
    description: string;
    requiredCapability: string;
    maxBudget: BigNumberish;
    agreedPrice: BigNumberish;
    deadline: BigNumberish;
    status: BigNumberish;
    disputeStatus: BigNumberish;
    specialist: AddressLike;
    resultHash: BytesLike;
    resultUrl: string;
    createdAt: BigNumberish;
    settledAt: BigNumberish;
    disputeWindowEnd: BigNumberish;
    childJobIds: BytesLike[];
  };

  export type JobStructOutput = [
    id: string,
    parentJobId: string,
    planner: string,
    description: string,
    requiredCapability: string,
    maxBudget: bigint,
    agreedPrice: bigint,
    deadline: bigint,
    status: bigint,
    disputeStatus: bigint,
    specialist: string,
    resultHash: string,
    resultUrl: string,
    createdAt: bigint,
    settledAt: bigint,
    disputeWindowEnd: bigint,
    childJobIds: string[]
  ] & {
    id: string;
    parentJobId: string;
    planner: string;
    description: string;
    requiredCapability: string;
    maxBudget: bigint;
    agreedPrice: bigint;
    deadline: bigint;
    status: bigint;
    disputeStatus: bigint;
    specialist: string;
    resultHash: string;
    resultUrl: string;
    createdAt: bigint;
    settledAt: bigint;
    disputeWindowEnd: bigint;
    childJobIds: string[];
  };
}

export interface JobEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DISPUTE_WINDOW"
      | "acceptBid"
      | "bid"
      | "cancelJob"
      | "escrow"
      | "getBids"
      | "getJob"
      | "markFailed"
      | "owner"
      | "postJob"
      | "raiseDispute"
      | "registry"
      | "releasePayout"
      | "resolveDispute"
      | "submitResult"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BidAccepted"
      | "BidReceived"
      | "DisputeRaised"
      | "DisputeResolved"
      | "JobCancelled"
      | "JobDelivered"
      | "JobFailed"
      | "JobPosted"
      | "PayoutReleased"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DISPUTE_WINDOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptBid",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bid",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelJob",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "escrow", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "getBids", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "getJob", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "markFailed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "postJob",
    values: [string, string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "raiseDispute",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "releasePayout",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "submitResult",
    values: [BytesLike, BytesLike, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "DISPUTE_WINDOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "acceptBid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancelJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "escrow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBids", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "markFailed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "postJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "raiseDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "releasePayout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitResult",
    data: BytesLike
  ): Result;
}

export namespace BidAcceptedEvent {
  export type InputTuple = [
    jobId: BytesLike,
    specialist: AddressLike,
    agreedPrice: BigNumberish
  ];
  export type OutputTuple = [
    jobId: string,
    specialist: string,
    agreedPrice: bigint
  ];
  export interface OutputObject {
    jobId: string;
    specialist: string;
    agreedPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BidReceivedEvent {
  export type InputTuple = [
    jobId: BytesLike,
    specialist: AddressLike,
    bidPrice: BigNumberish
  ];
  export type OutputTuple = [
    jobId: string,
    specialist: string,
    bidPrice: bigint
  ];
  export interface OutputObject {
    jobId: string;
    specialist: string;
    bidPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeRaisedEvent {
  export type InputTuple = [jobId: BytesLike, planner: AddressLike];
  export type OutputTuple = [jobId: string, planner: string];
  export interface OutputObject {
    jobId: string;
    planner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeResolvedEvent {
  export type InputTuple = [jobId: BytesLike, specialistFault: boolean];
  export type OutputTuple = [jobId: string, specialistFault: boolean];
  export interface OutputObject {
    jobId: string;
    specialistFault: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobCancelledEvent {
  export type InputTuple = [jobId: BytesLike];
  export type OutputTuple = [jobId: string];
  export interface OutputObject {
    jobId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobDeliveredEvent {
  export type InputTuple = [
    jobId: BytesLike,
    resultHash: BytesLike,
    resultUrl: string,
    disputeWindowEnd: BigNumberish
  ];
  export type OutputTuple = [
    jobId: string,
    resultHash: string,
    resultUrl: string,
    disputeWindowEnd: bigint
  ];
  export interface OutputObject {
    jobId: string;
    resultHash: string;
    resultUrl: string;
    disputeWindowEnd: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobFailedEvent {
  export type InputTuple = [jobId: BytesLike, specialist: AddressLike];
  export type OutputTuple = [jobId: string, specialist: string];
  export interface OutputObject {
    jobId: string;
    specialist: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobPostedEvent {
  export type InputTuple = [
    jobId: BytesLike,
    planner: AddressLike,
    capability: string,
    maxBudget: BigNumberish,
    parentJobId: BytesLike
  ];
  export type OutputTuple = [
    jobId: string,
    planner: string,
    capability: string,
    maxBudget: bigint,
    parentJobId: string
  ];
  export interface OutputObject {
    jobId: string;
    planner: string;
    capability: string;
    maxBudget: bigint;
    parentJobId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PayoutReleasedEvent {
  export type InputTuple = [
    jobId: BytesLike,
    specialist: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [jobId: string, specialist: string, amount: bigint];
  export interface OutputObject {
    jobId: string;
    specialist: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface JobEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): JobEscrow;
  waitForDeployment(): Promise<this>;

  interface: JobEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DISPUTE_WINDOW: TypedContractMethod<[], [bigint], "view">;

  acceptBid: TypedContractMethod<
    [jobId: BytesLike, specialist: AddressLike, agreedPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  bid: TypedContractMethod<
    [jobId: BytesLike, bidPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  cancelJob: TypedContractMethod<[jobId: BytesLike], [void], "nonpayable">;

  escrow: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  getBids: TypedContractMethod<
    [jobId: BytesLike],
    [JobEscrow.BidStructOutput[]],
    "view"
  >;

  getJob: TypedContractMethod<
    [jobId: BytesLike],
    [JobEscrow.JobStructOutput],
    "view"
  >;

  markFailed: TypedContractMethod<[jobId: BytesLike], [void], "nonpayable">;

  owner: TypedContractMethod<[], [string], "view">;

  postJob: TypedContractMethod<
    [
      description: string,
      capability: string,
      deadline: BigNumberish,
      parentJobId: BytesLike
    ],
    [string],
    "payable"
  >;

  raiseDispute: TypedContractMethod<[jobId: BytesLike], [void], "nonpayable">;

  registry: TypedContractMethod<[], [string], "view">;

  releasePayout: TypedContractMethod<[jobId: BytesLike], [void], "nonpayable">;

  resolveDispute: TypedContractMethod<
    [jobId: BytesLike, specialistFault: boolean],
    [void],
    "nonpayable"
  >;

  submitResult: TypedContractMethod<
    [jobId: BytesLike, resultHash: BytesLike, resultUrl: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DISPUTE_WINDOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "acceptBid"
  ): TypedContractMethod<
    [jobId: BytesLike, specialist: AddressLike, agreedPrice: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "bid"
  ): TypedContractMethod<
    [jobId: BytesLike, bidPrice: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cancelJob"
  ): TypedContractMethod<[jobId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "escrow"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBids"
  ): TypedContractMethod<
    [jobId: BytesLike],
    [JobEscrow.BidStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getJob"
  ): TypedContractMethod<
    [jobId: BytesLike],
    [JobEscrow.JobStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "markFailed"
  ): TypedContractMethod<[jobId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "postJob"
  ): TypedContractMethod<
    [
      description: string,
      capability: string,
      deadline: BigNumberish,
      parentJobId: BytesLike
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "raiseDispute"
  ): TypedContractMethod<[jobId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "releasePayout"
  ): TypedContractMethod<[jobId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [jobId: BytesLike, specialistFault: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitResult"
  ): TypedContractMethod<
    [jobId: BytesLike, resultHash: BytesLike, resultUrl: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BidAccepted"
  ): TypedContractEvent<
    BidAcceptedEvent.InputTuple,
    BidAcceptedEvent.OutputTuple,
    BidAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "BidReceived"
  ): TypedContractEvent<
    BidReceivedEvent.InputTuple,
    BidReceivedEvent.OutputTuple,
    BidReceivedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeRaised"
  ): TypedContractEvent<
    DisputeRaisedEvent.InputTuple,
    DisputeRaisedEvent.OutputTuple,
    DisputeRaisedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeResolved"
  ): TypedContractEvent<
    DisputeResolvedEvent.InputTuple,
    DisputeResolvedEvent.OutputTuple,
    DisputeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "JobCancelled"
  ): TypedContractEvent<
    JobCancelledEvent.InputTuple,
    JobCancelledEvent.OutputTuple,
    JobCancelledEvent.OutputObject
  >;
  getEvent(
    key: "JobDelivered"
  ): TypedContractEvent<
    JobDeliveredEvent.InputTuple,
    JobDeliveredEvent.OutputTuple,
    JobDeliveredEvent.OutputObject
  >;
  getEvent(
    key: "JobFailed"
  ): TypedContractEvent<
    JobFailedEvent.InputTuple,
    JobFailedEvent.OutputTuple,
    JobFailedEvent.OutputObject
  >;
  getEvent(
    key: "JobPosted"
  ): TypedContractEvent<
    JobPostedEvent.InputTuple,
    JobPostedEvent.OutputTuple,
    JobPostedEvent.OutputObject
  >;
  getEvent(
    key: "PayoutReleased"
  ): TypedContractEvent<
    PayoutReleasedEvent.InputTuple,
    PayoutReleasedEvent.OutputTuple,
    PayoutReleasedEvent.OutputObject
  >;

  filters: {
    "BidAccepted(bytes32,address,uint256)": TypedContractEvent<
      BidAcceptedEvent.InputTuple,
      BidAcceptedEvent.OutputTuple,
      BidAcceptedEvent.OutputObject
    >;
    BidAccepted: TypedContractEvent<
      BidAcceptedEvent.InputTuple,
      BidAcceptedEvent.OutputTuple,
      BidAcceptedEvent.OutputObject
    >;

    "BidReceived(bytes32,address,uint256)": TypedContractEvent<
      BidReceivedEvent.InputTuple,
      BidReceivedEvent.OutputTuple,
      BidReceivedEvent.OutputObject
    >;
    BidReceived: TypedContractEvent<
      BidReceivedEvent.InputTuple,
      BidReceivedEvent.OutputTuple,
      BidReceivedEvent.OutputObject
    >;

    "DisputeRaised(bytes32,address)": TypedContractEvent<
      DisputeRaisedEvent.InputTuple,
      DisputeRaisedEvent.OutputTuple,
      DisputeRaisedEvent.OutputObject
    >;
    DisputeRaised: TypedContractEvent<
      DisputeRaisedEvent.InputTuple,
      DisputeRaisedEvent.OutputTuple,
      DisputeRaisedEvent.OutputObject
    >;

    "DisputeResolved(bytes32,bool)": TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;
    DisputeResolved: TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;

    "JobCancelled(bytes32)": TypedContractEvent<
      JobCancelledEvent.InputTuple,
      JobCancelledEvent.OutputTuple,
      JobCancelledEvent.OutputObject
    >;
    JobCancelled: TypedContractEvent<
      JobCancelledEvent.InputTuple,
      JobCancelledEvent.OutputTuple,
      JobCancelledEvent.OutputObject
    >;

    "JobDelivered(bytes32,bytes32,string,uint256)": TypedContractEvent<
      JobDeliveredEvent.InputTuple,
      JobDeliveredEvent.OutputTuple,
      JobDeliveredEvent.OutputObject
    >;
    JobDelivered: TypedContractEvent<
      JobDeliveredEvent.InputTuple,
      JobDeliveredEvent.OutputTuple,
      JobDeliveredEvent.OutputObject
    >;

    "JobFailed(bytes32,address)": TypedContractEvent<
      JobFailedEvent.InputTuple,
      JobFailedEvent.OutputTuple,
      JobFailedEvent.OutputObject
    >;
    JobFailed: TypedContractEvent<
      JobFailedEvent.InputTuple,
      JobFailedEvent.OutputTuple,
      JobFailedEvent.OutputObject
    >;

    "JobPosted(bytes32,address,string,uint256,bytes32)": TypedContractEvent<
      JobPostedEvent.InputTuple,
      JobPostedEvent.OutputTuple,
      JobPostedEvent.OutputObject
    >;
    JobPosted: TypedContractEvent<
      JobPostedEvent.InputTuple,
      JobPostedEvent.OutputTuple,
      JobPostedEvent.OutputObject
    >;

    "PayoutReleased(bytes32,address,uint256)": TypedContractEvent<
      PayoutReleasedEvent.InputTuple,
      PayoutReleasedEvent.OutputTuple,
      PayoutReleasedEvent.OutputObject
    >;
    PayoutReleased: TypedContractEvent<
      PayoutReleasedEvent.InputTuple,
      PayoutReleasedEvent.OutputTuple,
      PayoutReleasedEvent.OutputObject
    >;
  };
}
